export class SoManagerDhruvaIndex {
    constructor(public soManagerEmpCode: string,
        public soManagerName: string,
        public doCount: string,
        public totalDhruva: string,
        public awesum: string,
        public facilityCompletion: string,
        public spotCheck: string,
        public caEvaluation: string,
        public activityCompletion: string,
        public mPower: string,
        public foQuiz: string,
        public rca: string,
        public caTraining: string,
        public telecall: string,
        public fit: string,
        public seva: string,
        public sauKaSankalp: string,
        public attainer: string,
        public xperience: string,
        public finalDhruvaIndex: string,
        public rank: string,
        public updatedOn: string,
        public dhruvaCompliant: string,
        public employeeLocation: string) { }
}