export class StateDhruvaIndex {
	constructor(
		public stateOfficeCode: number,
		public finalDhruvaIndex: number,
		public totalDhruva: number,
		public awesum: number,
		public awesumRank: number,
		public facilityCompletion: number,
		public facilityCompletionRank: number,
		public spotCheck: number,
		public spotCheckRank: number,
		public caEvaluation: number,
		public caEvaluationRank: number,
		public activityCompletion: number,
		public activityCompletionRank: number,
		public mPower: number,
		public mPowerRank: number,
		public foQuiz: number,
		public foQuizRank: number,
		public rca: number,
		public rcaRank: number,
		public caTraining: number,
		public caTrainingRank: number,
		public telecall: number,
		public telecallRank: number,
		public fit: number,
		public fitRank: number,
		public dsa: number,
		public dsaRank: number,
		public seva: number,
		public sevaRank: number,
		public sauKaSankalp: number,
		public sauKaSankalpRank: number,
		public attainer: number,
		public attainerRank: number,
		public xperience: number,
		public xperienceRank: number,
		public rank: number,
		public updatedOn: string,
		public dhruvaCompliant: number,
		public dhruvaCompliantRank: number,
		public soMaster: string) { }
}